### ISSUE TITLE
BouncingScrollPhysics not working

### ISSUE THREAD

**Issue by hyungtaecf** [fluttercandies/extended_tabs#13]
I'm trying to apply BouncingScrollPhysics when moving through the tabs but ClampingScrollPhysics is applied instead.

flutter doctor -v
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [versÃ£o 10.0.19041.746], locale pt-BR)
    • Flutter version 1.22.5 at C:\src\flutter
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
    • Android SDK at C:\Users\HTCF\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0-rc4
    • ANDROID_HOME = C:\Users\HTCF\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.2
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7547

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\HTCF\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (1 available)
    • Moto G Play (mobile) • 0026091935 • android-arm • Android 7.1.1 (API 25)

• No issues found!

**Comment by zmtzawqlp** [comment]
which version do you use?

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_tabs/blob/338c3d65d146d848d1f1aae8ff1f89038534861c/lib/src/tab_view.dart#L140

**Comment by hyungtaecf** [comment]
> which version do you use?

Thanks for answering so quickly, and I'm sorry because I didn't check if it was the last version.
I had an outdated version. I updated it and it worked fine!
