### ISSUE TITLE
Active Tab

### ISSUE THREAD

**Issue by acamenhas** [fluttercandies/extended_tabs#16]
Hello,

I have 4 tabs in my module, i want to open a tab by default based on a user variable.
If user is admin i want to open firstly on the last tab,...

How can i do that?

Thank you

**Comment by zmtzawqlp** [comment]
TabController(length: null, vsync: null, initialIndex: 3)

**Comment by acamenhas** [comment]
Hi @zmtzawqlp very fast answer, thank you!
Closing
