### ISSUE TITLE
三级Tab，有出现第一级不能滚动切换到情况

### ISSUE THREAD

**Issue by CarrySniper** [fluttercandies/extended_tabs#17]
提供的Demo是三级Tab的，滚动切换是正常的，这是同一children仅有一个孩子有多个分页。
但是，当同一children的孩子同时有多个分页就会在最后位置卡住，滚动切换不到另一级页面。
不知道是不是真正存在这个问题？

如下是正常的:
```
1 TAB0
1.1 - TAB00
 1.1.1 - - TAB000
 1.1.2 - - TAB001
1.2 - TAB01
2 TAB1
```
如下是会卡住的:
```
1 TAB0
1.1 - TAB00
1.1.1 - - TAB000
1.1.2 - - TAB001
1.2 - TAB01
1.2.1 - - TAB010
1.2.2 - - TAB011
2 TAB1
```

**Comment by zmtzawqlp** [comment]
。。。可怕。。。你这是多少层了。。。越多层，越来判断。。2层应该是完美的

**Comment by CarrySniper** [comment]
@zmtzawqlp 和demo一样，只有3层，只是第3层分类内容有点多。就因为特殊才发现这个问题，其他端不知道，iOS端是划不过去的。（场景：排行榜有男女榜，男女榜都有魅力榜和财富榜，每个榜又有总榜和月榜之类的，就这3层。现在只写了男榜TAB0的，TAB1的下面写不写无所谓，这个时候只能滚男榜的，过不了女榜那边）

**Comment by zmtzawqlp** [comment]
最好能提供一个能重现问题的最小demo

**Comment by CarrySniper** [comment]
@zmtzawqlp 只传了一个main.dart文件。https://github.com/CarrySniper/demo/blob/main/main.dart
彩虹色，绿色滚不过TAB1青色：第一次滚动太快会跨越绿色直接到青色，并注意到有报错提示。

**Comment by liuxinghudiejie** [comment]
> @zmtzawqlp 和demo一样，只有3层，只是第3层分类内容有点多。就因为特殊才发现这个问题，其他端不知道，iOS端是划不过去的。（场景：排行榜有男女榜，男女榜都有魅力榜和财富榜，每个榜又有总榜和月榜之类的，就这3层。现在只写了男榜TAB0的，TAB1的下面写不写无所谓，这个时候只能滚男榜的，过不了女榜那边）

好家伙，我以为是我写法有问题，我也是排行榜，也是三级联动，和你情况一样，滑下面两级，第一级别不会自动跟着滑动

**Comment by CarrySniper** [comment]
@liuxinghudiejie 我也不知道是不是写法问题，影响不是很大，就是体验没那么好。

**Comment by liuxinghudiejie** [comment]
> @liuxinghudiejie 我也不知道是不是写法问题，影响不是很大，就是体验没那么好。

我是3x3x3级，二三级可以联动，但是滑二三级的时候，第一级不会联动，只能手动点击第一级，你是这样吗

**Comment by CarrySniper** [comment]
> > @liuxinghudiejie 我也不知道是不是写法问题，影响不是很大，就是体验没那么好。
> 
> 我是3x3x3级，二三级可以联动，但是滑二三级的时候，第一级不会联动，只能手动点击第一级，你是这样吗

是这样的。我简单写的是2x2x2，就是3级。只能点击切换，或者滚动那三级TAB切换，滚动范围小了。

**Comment by liuxinghudiejie** [comment]
> > > @liuxinghudiejie 我也不知道是不是写法问题，影响不是很大，就是体验没那么好。
> > 
> > 
> > 我是3x3x3级，二三级可以联动，但是滑二三级的时候，第一级不会联动，只能手动点击第一级，你是这样吗
> 
> 是这样的。我简单写的是2x2x2，就是3级。只能点击切换，或者滚动那三级TAB切换，滚动范围小了。

对对对，我也是这样

**Comment by zmtzawqlp** [comment]
试试最新的版本 https://github.com/fluttercandies/extended_tabs/commit/640f3770c4822473bcc21f0a8ca5f18abe551da0

**Comment by CarrySniper** [comment]
感谢你的来信。
 
你的来信已经发送到CJQ处。

**Comment by CarrySniper** [comment]
感谢你的来信。
 
你的来信已经发送到CJQ处。
