### ISSUE TITLE
当Tab过多   可以滚动的时候 ，tab与tab 之间没有间距。

### ISSUE THREAD

**Issue by desire0420** [fluttercandies/extended_tabs#18]
当Tab过多   可以滚动的时候 ，tab与tab 之间没有间距。请问要怎么解决
![image](https://user-images.githubusercontent.com/12178442/124112553-fb409880-da9c-11eb-93c8-fd1596964f46.png)

**Comment by zmtzawqlp** [comment]
ExtendedTabBar(
              tabs: List<Widget>.generate(
                  _controller.length,
                  (int index) => Tab(
                        text: 'Tab$index',
                      )).toList(),
              controller: _controller,
              labelPadding: EdgeInsets.symmetric(horizontal: 30),
              labelColor: Colors.blue,
              isScrollable: _controller.length > 5,
              indicatorSize: _tabBarIndicatorSize,
              mainAxisAlignment: _mainAxisAlignment,
              indicator: const ExtendedUnderlineTabIndicator(
                  //size: 31,
                  insets: EdgeInsets.symmetric(horizontal: 30),
                  borderSide: BorderSide(
                    color: Colors.red,
                    width: 1,
                  )),
            )
