### ISSUE TITLE
tab切换，生命周期

### ISSUE THREAD

**Issue by sanjin123** [fluttercandies/extended_tabs#19]
当存在有tab0，tab1，tab2，tab3，四个tab时：
从tab0->tab3时，调用为：
tab3.initState
tab0.dispose
然后从tab3->tab1时，调用为：
tab2.initState
tab2.dispose
tab1.initState
tab3.dispose
这里有办法不然他调用到tab2的initState和dispose方法吗？

**Comment by zmtzawqlp** [comment]
没有，有过渡动画。会从0，1，2 到3
