### ISSUE TITLE
ExtendedTabBarView嵌套ExtendedTabBarView联动滑动bug

### ISSUE THREAD

**Issue by wtwsky** [fluttercandies/extended_tabs#24]
在英语环境没问题，啊语环境有问题，看了一下源码，应该是_handleAncestorOrChild里面处理手势方向有问题，没有兼容啊语的手势方向
` /// 这里的判断有问题` 
`
 if ((delta < 0 &&
              _position!.extentAfter == 0 &&
              state!._position!.extentAfter != 0) ||
          (delta > 0 &&
              _position!.extentBefore == 0 &&
              state!._position!.extentBefore != 0))`

**Comment by zmtzawqlp** [comment]
已修复
