### ISSUE TITLE
flutter3.0.5版本下滚动失效

### ISSUE THREAD

**Issue by ss-huacha** [fluttercandies/extended_tabs#25]
flutter3.0.5版本
外层是 pageview 内层ExtendedTabBarView滚动失效

**Comment by zmtzawqlp** [comment]
pageview？官方的？ 那怎么会支持呢？

**Comment by ss-huacha** [comment]
是pageview里面有 两个tabbar，手势滑动两个tabbar都不滚动只有pageview滚动

**Comment by ss-huacha** [comment]
在flutter2.10.5还是正常的

**Comment by zmtzawqlp** [comment]
那可能只是凑巧

**Comment by zmtzawqlp** [comment]
runnable demo
