### ISSUE TITLE
[Discussions] 

### ISSUE THREAD

**Issue by yanmingLiu** [fluttercandies/extended_tabs#36]
### Content

如果添加一个header在上方呢，类似sliver那样

**Comment by zmtzawqlp** [comment]
不懂你的意思

**Comment by yanmingLiu** [comment]
> 不懂你的意思

可以的，你这个库很 nice.(ʘ▽ʘ)👍给大佬👍外层再套一个 Nest 就可以了![正在上传 
![image](https://github.com/fluttercandies/extended_tabs/assets/19849661/d9e9e419-9065-4924-9cbc-2a335089eece)


大概意思就是类似下面这种，但是需要多层 tab 

![image](https://github.com/fluttercandies/extended_tabs/assets/19849661/ef9cf3f7-0785-4153-be51-ef4076d73a5a)
