### ISSUE TITLE
Child ExtendedTabBarView doesn't change by TabController.animate()

### ISSUE THREAD

**Issue by sil-main-coo** [fluttercandies/extended_tabs#6]
I'm trying to programmatically change between tabs inside the app. 
tabController.animateTo() only change the TabBar, but not ExtendedTabBarView.

**Comment by zmtzawqlp** [comment]
i didn't get your point without code

**Comment by sil-main-coo** [comment]
I have a expanded menu drawer in Scaffold. How to integrate it with your child?

**Comment by zmtzawqlp** [comment]
reopen if has any other issue
