### ISSUE TITLE
滑动tab滚动异常

### ISSUE THREAD

**Issue by Eddiegooo** [fluttercandies/extended_tabs#9]
你好！
**问题点：** 横向切换tab，切换完立即进行界面上滑操作，此时不能响应上滑手势事件，还是在响应横向切换tab事件。

**复现步骤：** 在切换tab的过程中，刚切换到下一个tab，此时迅速进行上滑界面操作。

**Comment by zmtzawqlp** [comment]
这是官方的默认行为，手势竞技场
